In [1]:
import pandas as pd
from sklearn.metrics import f1_score, auc, roc_curve
import numpy as np

In [3]:
# path = "/home/workspace/inference_result/CXR/llama_7b_mimic_result_dabin.csv"
# path = "/home/workspace/inference_result/CXR/llama_13b_mimic_result_dabin.csv"
# path = "/home/workspace/inference_result/CXR/llama-30b_mimic_result_dabin.csv"
# path = "/home/workspace/inference_result/CXR/dabin_llama-65b-MIMIC.csv"
# path = "/home/workspace/inference_result/CXR/dabin_llama-65b_NSHOT3-MIMIC.csv"
path = "/home/workspace/inference_result/CXR/dabin_llama-65b_NSHOT3-MIMIC_4.csv"
# path = "/home/workspace/inference_result/CXR/dabin_llama-65b_NSHOT0-MIMIC.csv"
# path = "/home/workspace/inference_result/CXR/dabin_llama-65b_NSHOT0-MIMIC_2.csv"

# path = "/home/workspace/inference_result/CXR/llama2_7b_mimic_result_dabin.csv"
# path = "/home/workspace/inference_result/CXR/llama2_13b_mimic_result_dabin.csv"
# path = "/home/workspace/inference_result/CXR/llama2-70b_mimic_result_dabin.csv"

# path = "/home/workspace/inference_result/CXR/chexpert_mimic_dabin.csv"
# path = "/home/workspace/inference_result/CXR/chexbert_mimic_dabin.csv"

# path = "/home/workspace/inference_result/CXR/Llama-2-70b-hf_NSHOT3-MIMIC_dabin.csv"
# path = "/home/workspace/inference_result/CXR/Llama-2-70b-hf_NSHOT10-MIMIC_dabin.csv"


pred = pd.read_csv(path)

In [4]:
pred

,Enlarged Cardiomediastinum,Cardiomegaly,Lung Lesion,Lung Opacity,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,0,0,2,2,0,0,2,1,0,0,2,0,0
1,0,0,2,1,0,2,2,2,0,0,2,2,2
2,2,2,1,1,2,1,1,2,0,0,2,2,2
3,1,1,2,2,2,2,2,2,0,0,2,2,2
4,0,-1,2,2,2,2,2,1,0,1,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0,2,2,0,2,0,2,2,0,0,2,2,2
496,0,0,1,1,2,1,2,1,0,1,2,1,2
497,0,2,2,2,2,2,2,2,0,0,2,0,2
498,0,0,2,2,0,0,2,2,0,-1,2,0,0
499,0,0,2,2,0,0,2,2,0,0,2,1,2

In [5]:
true = pd.read_csv('/home/data/CXR_Labeler/mimic_500_answer_dabin.csv')
pred.columns =true.columns

In [6]:
true

,Enlarged Cardiomediastinum,Cardiomegaly,Lung Lesion,Lung Opacity,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,1,2,2,2,2,0,2,1,0,0,2,2,1
1,0,2,2,1,0,2,2,2,0,0,2,2,2
2,0,0,2,1,0,1,1,2,0,0,2,2,2
3,0,1,2,2,0,2,2,2,0,0,2,2,2
4,0,-1,2,2,2,2,0,1,0,0,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0,2,2,2,2,2,2,2,0,0,2,2,1
496,2,0,-1,2,2,0,2,1,2,-1,2,1,2
497,0,2,2,2,2,2,2,2,2,2,2,2,2
498,0,2,2,2,0,0,2,2,2,-1,2,2,2
499,0,2,2,2,0,0,2,2,0,0,0,1,1

In [7]:
drop_idx = []

#mimic
#llama2 7b 
# drop_idx = [239]

# llama2 70b 
# drop_idx = [6, 64, 129, 157, 223, 224, 307, 351, 429]

# llama2 70b 3-shot
# drop_idx = [102, 340, 448, 484]

In [8]:
pred = pred.drop(drop_idx)
true = true.drop(drop_idx).reset_index(drop=True)

In [9]:
pred

,Enlarged Cardiomediastinum,Cardiomegaly,Lung Lesion,Lung Opacity,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,0,0,2,2,0,0,2,1,0,0,2,0,0
1,0,0,2,1,0,2,2,2,0,0,2,2,2
2,2,2,1,1,2,1,1,2,0,0,2,2,2
3,1,1,2,2,2,2,2,2,0,0,2,2,2
4,0,-1,2,2,2,2,2,1,0,1,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0,2,2,0,2,0,2,2,0,0,2,2,2
496,0,0,1,1,2,1,2,1,0,1,2,1,2
497,0,2,2,2,2,2,2,2,0,0,2,0,2
498,0,0,2,2,0,0,2,2,0,-1,2,0,0
499,0,0,2,2,0,0,2,2,0,0,2,1,2

In [10]:
true

,Enlarged Cardiomediastinum,Cardiomegaly,Lung Lesion,Lung Opacity,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,1,2,2,2,2,0,2,1,0,0,2,2,1
1,0,2,2,1,0,2,2,2,0,0,2,2,2
2,0,0,2,1,0,1,1,2,0,0,2,2,2
3,0,1,2,2,0,2,2,2,0,0,2,2,2
4,0,-1,2,2,2,2,0,1,0,0,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0,2,2,2,2,2,2,2,0,0,2,2,1
496,2,0,-1,2,2,0,2,1,2,-1,2,1,2
497,0,2,2,2,2,2,2,2,2,2,2,2,2
498,0,2,2,2,0,0,2,2,2,-1,2,2,2
499,0,2,2,2,0,0,2,2,0,0,0,1,1

In [11]:
import numpy as np
import pandas as pd
from sklearn.metrics import f1_score
from scipy import stats

def bootstrap_sample(df_pred, df_true, seed=None):
    np.random.seed(seed)
    n = len(df_pred)
    indices = np.random.choice(n, n, replace=True)
    new_pred = df_pred.iloc[indices].reset_index(drop=True)
    new_true = df_true.iloc[indices].reset_index(drop=True)
    return new_pred, new_true

def get_all_f1(true, pred, average):
    all_f1 = []
    for i in range(len(true.columns)):
        all_f1.append(f1_score(true.iloc[:,i], pred.iloc[:,i], average=average))
    return all_f1

all_f1_scores_weighted = []
all_f1_scores_macro = []
all_f1_scores_micro = []
for i in range(10):
    new_pred, new_true = bootstrap_sample(pred, true, seed=i)
    f1_weighted = get_all_f1(new_true, new_pred, average='weighted')
    f1_macro = get_all_f1(new_true, new_pred, average='macro')
    f1_micro = get_all_f1(new_true, new_pred, average='micro')
    all_f1_scores_weighted.append(f1_weighted)
    all_f1_scores_macro.append(f1_macro)
    all_f1_scores_micro.append(f1_micro)

def calculate_mean_std(scores_list):
    mean_scores = np.mean(scores_list, axis=0)
    std_scores = np.std(scores_list, axis=0)
    return mean_scores, std_scores

def calculate_confidence_interval(scores_list, confidence=0.95):
    mean_scores, std_scores = calculate_mean_std(scores_list)
    se = std_scores / np.sqrt(len(scores_list))
    h = se * stats.t.ppf((1 + confidence) / 2., len(scores_list) - 1)
    return mean_scores - h, mean_scores + h

# 평균, 표준편차 및 95% 신뢰구간 계산
average_f1_weighted, std_f1_weighted = calculate_mean_std(all_f1_scores_weighted)
ci_f1_weighted_1, ci_f1_weighted_2 = calculate_confidence_interval(all_f1_scores_weighted)

average_f1_macro, std_f1_macro = calculate_mean_std(all_f1_scores_macro)
ci_f1_macro_1, ci_f1_macro_2 = calculate_confidence_interval(all_f1_scores_macro)

average_f1_micro, std_f1_micro = calculate_mean_std(all_f1_scores_micro)
ci_f1_micro_1, ci_f1_micro_2 = calculate_confidence_interval(all_f1_scores_micro)

In [12]:
result_df = pd.DataFrame([average_f1_weighted, average_f1_macro, average_f1_micro]).transpose()

In [13]:
average_macro_f1 = [np.mean(f1) for f1 in all_f1_scores_macro]
pd.DataFrame(average_macro_f1)

          0
0  0.527849
1  0.489695
2  0.500971
3  0.482328
4  0.521195
5  0.516329
6  0.482503
7  0.494377
8  0.471963
9  0.493128

In [14]:
result_df

           0         1       2
0   0.478105  0.270728  0.5374
1   0.580098  0.503237  0.5996
2   0.900976  0.476010  0.8674
3   0.851107  0.449254  0.8442
4   0.611170  0.454142  0.6218
5   0.730677  0.664989  0.7318
6   0.837220  0.415986  0.8586
7   0.918352  0.492986  0.9246
8   0.791128  0.590387  0.8386
9   0.837542  0.605835  0.8608
10  0.890432  0.404213  0.8962
11  0.771856  0.534795  0.7674
12  0.855107  0.611879  0.8520

In [15]:
ci_df = pd.DataFrame([ci_f1_weighted_1, ci_f1_weighted_2, ci_f1_macro_1, ci_f1_macro_2, ci_f1_micro_1, ci_f1_micro_2]).transpose()

In [16]:
ci_df

           0         1         2         3         4         5
0   0.466691  0.489519  0.260726  0.280730  0.526597  0.548203
1   0.562893  0.597303  0.493977  0.512498  0.583826  0.615374
2   0.892216  0.909736  0.419159  0.532861  0.853963  0.880837
3   0.837763  0.864451  0.420251  0.478257  0.831687  0.856713
4   0.597177  0.625162  0.441493  0.466791  0.609044  0.634556
5   0.716338  0.745016  0.616454  0.713524  0.717587  0.746013
6   0.823921  0.850519  0.394166  0.437805  0.847628  0.869572
7   0.910951  0.925754  0.480335  0.505636  0.916607  0.932593
8   0.774284  0.807973  0.519810  0.660964  0.826698  0.850502
9   0.830035  0.845048  0.570592  0.641079  0.855555  0.866045
10  0.881786  0.899079  0.381228  0.427198  0.889149  0.903251
11  0.762888  0.780823  0.474409  0.595181  0.757844  0.776956
12  0.840783  0.869431  0.585811  0.637947  0.840202  0.863798

In [17]:
average = [np.mean(all_f1_scores_macro[i]) for i in range(10)]
print(np.mean(average))
print(calculate_confidence_interval(average))

0.49803391270184105
(0.48555464171816615, 0.510513183685516)

In [18]:
average = [np.mean(all_f1_scores_weighted[i]) for i in range(10)]
print(np.mean(average))
print(calculate_confidence_interval(average))

0.7733669181457975
(0.7702971065968256, 0.7764367296947694)